# Generated by Django 4.0 on 2021-12-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=60)),
                ('jobDescribtion', models.TextField()),
                ('jobLocation', models.CharField(max_length=60)),
                ('jobCategories', models.CharField(choices=[('P', 'Pet Care'), ('E', 'Electronical'), ('G', 'Garden')], max_length=1)),
                ('isAdded', models.BooleanField(default=False)),
            ],
        ),
    ]
