# Generated by Django 4.0 on 2021-12-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HandyHelperDjango', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
