# Generated by Django 4.0 on 2021-12-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_alter_users_email_alter_users_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=60, unique=True)),
                ('jobDescribtion', models.TextField()),
                ('jobLocation', models.CharField(max_length=60)),
                ('jobCategories', models.CharField(choices=[('P', 'Pet Care'), ('E', 'Electronical'), ('G', 'Garden'), ('O', 'Others')], max_length=1)),
                ('isAdded', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.users')),
            ],
        ),
    ]
