# Generated by Django 4.0 on 2021-12-28 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobCategories',
        ),
    ]
