# Generated by Django 4.0 on 2021-12-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0002_remove_job_jobcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobTitle',
            field=models.CharField(error_messages={'unique': 'There is a job under the same title'}, max_length=60, unique=True),
        ),
    ]
