# Generated by Django 4.0 on 2021-12-28 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_alter_job_jobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
