# Generated by Django 4.0 on 2021-12-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0005_category_job_jobcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobCategory',
            field=models.CharField(choices=[('Pet care', 'Pet care'), ('Coding', 'Coding'), ('Electronic', 'Electronic'), ('Buying things', 'Buying things'), ('Garden', 'Garden'), ('Other', 'Other')], default='Other', max_length=60),
        ),
    ]
