# Generated by Django 4.0 on 2021-12-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0006_alter_job_jobcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
