# Generated by Django 4.0 on 2021-12-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0007_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobCategory',
        ),
        migrations.AddField(
            model_name='job',
            name='jobCategory',
            field=models.ManyToManyField(related_name='job', to='Job.Category'),
        ),
    ]
