# Generated by Django 4.0 on 2021-12-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0008_remove_job_jobcategory_job_jobcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobCategory',
            field=models.ManyToManyField(to='Job.Category'),
        ),
    ]
