# Generated by Django 4.0 on 2021-12-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0009_alter_job_jobcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='jobCategory',
        ),
        migrations.AddField(
            model_name='job',
            name='jobCategory',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('Coding', 'Coding'), ('Garden', 'Garden'), ('Pet Care', 'Pet Care'), ('Other', 'Other'), ('Buying things', 'Buying things')], default='Other', max_length=60),
        ),
    ]
