# Generated by Django 4.0 on 2021-12-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0010_remove_job_jobcategory_job_jobcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Buying things', 'Buying things'), ('Pet Care', 'Pet Care'), ('Garden', 'Garden'), ('Electronic', 'Electronic'), ('Other', 'Other'), ('Coding', 'Coding')], max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='job',
            name='jobCategory',
        ),
        migrations.AddField(
            model_name='job',
            name='jobCategory',
            field=models.ManyToManyField(to='Job.Category'),
        ),
    ]
