# Generated by Django 4.0 on 2022-01-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0012_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Coding', 'Coding'), ('Garden', 'Garden'), ('Buying things', 'Buying things'), ('Electronic', 'Electronic'), ('Pet Care', 'Pet Care'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobCategory',
            field=models.ManyToManyField(related_name='jobs_related', to='Job.Category'),
        ),
    ]
